// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness),
        lang = _assets_lang_dart._(brightness: brightness);

  final _assets_icons_dart icons;
  final _assets_images_dart images;
  final _assets_lang_dart lang;
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final 18_png = 'assets/icons/18.png';
  final 24_png = 'assets/icons/24.png';
  final 7_png = 'assets/icons/7.png';
  final ic_round_corporate_fare_png = 'assets/icons/ic_round-corporate-fare.png';
  final local_fire_department_png = 'assets/icons/local_fire_department.png';
  final material_symbols_real_estate_agent_rounded_png = 'assets/icons/material-symbols_real-estate-agent-rounded.png';
  final offer_png = 'assets/icons/offer.png';
  final rectagle_png = 'assets/icons/rectagle.png';
  final tm_png = 'assets/icons/tm.png';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness,
        categories_images = _assets_images_categories_images_dart._(brightness: brightness),
        products = _assets_images_products_dart._(brightness: brightness);

  final _assets_images_categories_images_dart categories_images;
  final _assets_images_products_dart products;
}

class _assets_images_categories_images_dart {
  final Brightness _brightness;

  _assets_images_categories_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final beauty_png = 'assets/images/categories_images/beauty.png';
  final man_png = 'assets/images/categories_images/man.png';
  final mobile_png = 'assets/images/categories_images/mobile.png';
  final watch_png = 'assets/images/categories_images/watch.png';
}

class _assets_images_products_dart {
  final Brightness _brightness;

  _assets_images_products_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Picture_3_png = 'assets/images/products/Picture-3.png';
  final Picture_png = 'assets/images/products/Picture.png';
  final sweet_shirt_png = 'assets/images/products/sweet_shirt.png';
}

class _assets_lang_dart {
  final Brightness _brightness;

  _assets_lang_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final ar_json = 'assets/lang/ar.json';
  final en_json = 'assets/lang/en.json';
}
